# Generated by Django 4.1.3 on 2023-01-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='query',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phoneno',
        ),
    ]
