# Generated by Django 4.1.3 on 2023-01-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contact_date_alter_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.IntegerField()),
                ('Name', models.CharField(max_length=120)),
                ('bill', models.IntegerField()),
            ],
        ),
    ]
