# Generated by Django 4.1.3 on 2023-01-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.IntegerField()),
                ('Name', models.CharField(default='', max_length=120)),
                ('bill', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='customer_details',
        ),
    ]
