# Generated by Django 4.1.3 on 2023-01-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_users_remove_user_fname_remove_user_lname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
